/** All provided external URLs in order (duplicates preserved for audit). */
export const PROVIDED_URLS = [
	'https://arkascendedcheats.com/',
	'https://deadsidecheats.net/',
	'https://arcraiderscheat.net/',
	'https://genshincheats.net/',
	'https://dbdcheats.net/',
	'https://tarkovcheats.net/',
	'https://unturnedcheats.net/',
	'https://unturnedcheats.com/',
	'https://warthundercheats.com/',
	'https://arcraiderscheat.net/',
	'https://genshincheats.net/',
	'https://dbdcheats.net/',
	'https://arcraiderscheat.net/',
	'https://genshincheats.net/',
	'https://dbdcheats.net/',
	'https://tarkovcheats.net/',
	'https://fortniteaimbot.com/',
	'https://marathoncheats.org/',
	'https://battlefieldcheats.org/',
	'https://lolcheats.org/',
	'https://warzonecheats.org/',
	'https://valocheats.com/',
	'https://grayzonecheats.com/',
	'https://arcraiderscheats.org/',
	'https://tarkovcheats.org/',
	'https://overwatchhacks.com/',
	'https://dbdcheats.org/',
	'https://theislehacks.org/',
	'https://islecheats.net/',
	'https://warthunderhacks.com/',
	'https://marathoncheats.cc/',
	'https://besttarkovcheats.com/',
	'https://thefinalscheats.org/',
	'https://dayzcheat.net/',
	'https://fncheats.net/',
	'https://islecheat.com/',
	'https://deadsidecheats.com/',
	'https://marvelrivalscheat.net/',
	'https://meccacheats.com/',
	'https://rusthack.net/',
	'https://grayzonecheats.net/',
	'https://unturnedhacks.com/',
	'https://palworldhack.net/',
	'https://r6siegecheats.net/',
	'https://eftcheat.net/',
	'https://eftcheat.net/',
	'https://calibercheats.com/',
	'https://codcheats.net/',
	'https://huntcheats.com/',
	'https://lolcheat.net/',
	'https://marathonhacks.net/',
	'https://mecchahacks.com/',
	'https://palworldhack.com/',
	'https://tarkovhack.net/',
	'https://warthundercheats.net/',
	'https://huntshowdowncheats.com/',
	'https://destiny2cheats.com/',
	'https://tarkovhacks.net/',
	'https://r6siegecheats.com/',
	'https://sandraiderscheat.com/',
	'https://palworldhacks.com/',
	'https://squadhacks.com/',
	'https://eftcheats.net/',
	'https://marathonhack.net/',
	'https://abicheats.com/',
	'https://bodycamcheats.com/',
	'https://grayzonehacks.com/',
	'https://lolcheats.net/',
	'https://oncehumanhacks.com/',
	'https://palworldhacks.net/',
	'https://reforgercheats.com/',
	'https://rivalshacks.com/',
	'https://oncehumancheats.net/',
	'https://overwatchcheat.net/',
	'https://dayzhack.net/',
	'https://battlefieldcheat.com/',
	'https://abihacks.com/',
	'https://arcraidershack.com/',
	'https://backroomscheats.com/',
	'https://marvelrivalshacks.net/',
	'https://mecchachameleonhacks.com/',
	'https://mecchachameleonhacks.net/',
	'https://overwatch2cheats.com/',
	'https://sandraiderscheats.com/',
	'https://rivalscheats.net/',
	'https://squadcheat.com/',
	'https://sandraidersofsophiecheats.net/',
	'https://tarkovcheat.net/',
	'https://thefinalscheats.net/',
	'https://theislehacks.net/',
	'https://valoranthack.net/',
	'https://warzonehacks.net/',
	'https://thefrontcheats.com/',
	'https://lostarkcheats.net/',
	'https://valoranthacks.org/',
	'https://siegehacks.com/',
	'https://warframehacks.com/',
	'https://warframecheat.com/',
	'https://narakacheats.org/',
	'https://minecraftcheat.com/',
	'https://destiny2hack.com/',
	'https://poecheats.com/',
	'https://genshinhacks.com/',
	'https://arcraiderscheat.org/',
	'https://palworldcheats.org/',
	'https://theislecheat.net/',
	'https://tarkovcheat.org/',
	'https://theislecheats.org/',
	'https://raftcheats.com/',
	'https://sandhacks.com/',
	'https://seaofthievescheats.net/',
	'https://battlefieldhacks.net/',
	'https://thefinalshacks.com/',
	'https://deltaforcecheats.org/',
	'https://warthunderhacks.net/',
	'https://valohacks.com/',
	'https://dbdcheat.org/',
	'https://arkcheats.net/',
	'https://unturnedcheats.org/',
	'https://warthundercheats.org/',
	'https://seaofthievescheats.org/',
	'https://warframecheats.net/',
	'https://arkascendedcheats.com/',
	'https://dunecheats.com/',
	'https://wutheringwavescheats.org/',
	'https://genshincheats.org/',
	'https://narakahacks.com/',
	'https://huntcheats.net/',
	'https://combatmastercheats.com/',
	'https://combatmastercheats.net/',
	'https://dunecheats.net/',
	'https://fncheat.com/',
	'https://deltaforcecheat.org/',
	'https://combatmastercheats.org/',
	'https://foxholecheats.com/',
	'https://foxholecheats.net/',
	'https://seaofthievescheat.net/',
	'https://marvelrivalshack.com/',
	'https://thefinalshack.com/',
	'https://exobornecheats.com/',
	'https://marvelrivalshack.net/',
	'https://codhacks.net/',
	'https://nba2k26cheats.net/',
	'https://nba2k26cheats.com/',
	'https://destiny2hacks.net/',
	'https://bodycamcheats.net/',
	'https://tf2cheats.org/',
	'https://deadsidecheat.com/',
	'https://codhacks.net/',
	'https://enlistedcheat.org/',
	'https://scumcheats.org/',
	'https://nba2k26hacks.com/',
	'https://deadsidecheats.org/',
	'https://warframehacks.net/',
	'https://nba2k26cheats.org/',
	'https://groundedcheats.net/',
	'https://groundedcheats.com/',
	'https://groundedhacks.net/',
	'https://groundedhacks.org/',
	'https://enlistedhacks.net/',
	'https://enlistedhacks.com/',
];

export function normalizeUrl(url) {
	const parsed = new URL(url.startsWith('http') ? url : `https://${url}`);
	parsed.protocol = 'https:';
	parsed.hash = '';
	let path = parsed.pathname.replace(/\/+$/, '') || '';
	return `${parsed.hostname}${path}`.toLowerCase();
}

export function urlToSlug(url) {
	const key = normalizeUrl(url);
	return `guide-${key.replace(/\./g, '-')}`;
}

export function getUniqueUrls() {
	const seen = new Set();
	const unique = [];
	for (const raw of PROVIDED_URLS) {
		const key = normalizeUrl(raw);
		if (seen.has(key)) continue;
		seen.add(key);
		const href = raw.startsWith('http') ? raw : `https://${raw}`;
		const normalized = new URL(href);
		normalized.protocol = 'https:';
		if (!normalized.pathname.endsWith('/')) normalized.pathname += '/';
		unique.push(normalized.href);
	}
	return unique;
}
